### ISSUE TITLE
[Question] Why is this actions useful?

### ISSUE THREAD

**Issue by jjangga0214** [sergioramos/yarn-actions#1]
`npm` and `yarn` can be directly used on VMs of ubuntu, macOS, and Windows. [actions/setup-node](https://github.com/actions/setup-node) can be indirectly used to set the version of `npm` and `yarn` along with `node`. 
 
So, I am curious why and where **yarn-actions** would be advantageous.

**Comment by rohmanhm** [comment]
Hi @sergioramos Why do you closed this issue without any clear explanation?
